### ISSUE TITLE
Parallelism not working as expected

### ISSUE THREAD

**Issue by abdheshkumar** [47deg/freestyle#196] opened 2017-04-13 12:27 UTC
We recently found the weird behavior of parallelism with freestyle. Details below:

Algebra:
```scala
@free
  trait Validation[F[_]] {
    def minSize(n: Int): FreeS.Par[F, Boolean]
    def hasNumber: FreeS.Par[F, Boolean]
  }
```
Interpreter:
```scala
import cats.data.Kleisli

import scala.concurrent.Future
import scala.concurrent.ExecutionContext.Implicits.global

object Interpreters {

  import Algebra._

  type ParValidator[A] = Kleisli[Future, String, A]


  implicit val interpreter = new Validation.Handler[ParValidator] {
    def minSize(n: Int): ParValidator[Boolean] =
      Kleisli { s =>
        Future {
          println("x before")
          Thread.sleep(4000)
          println("x after")
          s.size >= n
        }
      }

    def hasNumber: ParValidator[Boolean] =
      Kleisli { s =>
        Future {
          println("y before")
          Thread.sleep(100)
          println("y after")
          s.exists(c => "0123456789".contains(c))
        }
      }
  }
}
```
Test1:
```scala
"program with for-expression running in nondeterminism style" in {
    import cats.implicits._
    import scala.concurrent.ExecutionContext.Implicits.global
    import Algebra._
    import Interpreters._
    import freestyle.nondeterminism._
    import freestyle.implicits._

    val validation = Validation[Validation.Op]
    import validation._
    val k = for {
      one <- (minSize(3) |@| hasNumber).map(_ :: _ :: Nil)
    }yield (one)
    val validator     = k.exec[ParValidator]
    Await.result(validator.run("a"), Duration.Inf) shouldBe List(false, false)
  }
```
```
Output:(nondeterminism)
x before
y before
y after
x after
```

Tes2:

```scala
"program with for-expression running in determinism style because of `tupled.freeS`" in {
    import cats.implicits._
    import scala.concurrent.ExecutionContext.Implicits.global
    import Algebra._
    import Interpreters._
    import freestyle.nondeterminism._
    import freestyle.implicits._

    val validation = Validation[Validation.Op]
    import validation._
    val k = for {
      one <- (minSize(3) |@| hasNumber).tupled.freeS
    }yield (one)
    val validator     = k.exec[ParValidator]
    Await.result(validator.run("a"), Duration.Inf) shouldBe (false, false)
  }
```
Output:(determinism)
```
x before
x after
y before
y after
```
We found that `hasNumber` is blocked till `minSize` is completed. So I think the issue is between `map` and `tupled.freeS`.
If you want to run a complete program, you can clone it from here https://github.com/abdheshkumar/freestyle-example/blob/master/src/test/scala/FreeFutureTest.scala

**Comment by peterneyens** [comment] 2017-04-19 14:27
This actually has nothing to do with `map` versus `tupled`, but with using `freeS` or  not using `.freeS`.

Calling `freeS` on `(minSize(3) |@| hasNumber).tupled` lifts the `FreeS.Par[Validation.Op, (Boolean, Boolean)]`
into a `FreeS[Validation.Op, (Boolean, Boolean)]`.

The difference between calling `exec[ParValidator]` on `FreeS.Par` or `FreeS` is that the first one uses the `Applicative[ParValidator]` instance where the second one uses the `Monad[ParValidator]` instance.

The problem is that the `Monad` instance of `Kleisli` doesn't override the `product` method, which is used by `map` and `tupled` of the cartesian builder. This means that the two `Future` operations are executed sequentially.

PR https://github.com/typelevel/cats/pull/1618 should solve this in the next Cats version.

**Comment by peterneyens** [comment] 2017-04-21 07:34
Now that the Cats PR is merged, I am going ahead and close this issue.

---
If you want to try this before the next Cats release, you can provide your own `Monad` instance for `Kleisli` and use `foldMap` with a bit more work than `exec`.

```scala
val foo: FreeS[Validation.Op, (Boolean, Boolean)] =
  (minSize(3) |@| hasNumber).tupled.freeS

// a bit more work than  foo.exec[ParValidator] ...
val parValidatorMonad = kleisliMonad[Future, String]
val parInterpreter: ParInterpreter[Validation.Op, ParValidator] =
  interpretAp(parValidatorMonad, implicitly[Algebra.Validation.Handler[ParValidator]]))

val result: ParValidator[(Boolean, Boolean)] = foo.foldMap(parInterpreter)

def kleisliMonad[F[_], A](implicit F: Monad[F]) = new Monad[Kleisli[F, A, ?]] {
  def flatMap[B, C](fa: Kleisli[F, A, B])(f: B => Kleisli[F, A, C]): Kleisli[F, A, C] =
    fa.flatMap(f)

  def tailRecM[B, C](b: B)(f: B => Kleisli[F, A, Either[B, C]]): Kleisli[F, A, C] =
    Kleisli[F, A, C]({ a => F.tailRecM(b) { f(_).run(a) } })

  def pure[B](x: B): Kleisli[F, A, B] =
    Kleisli.pure[F, A, B](x)

  override def ap[B, C](f: Kleisli[F, A, B => C])(fa: Kleisli[F, A, B]): Kleisli[F, A, C] =
    fa.ap(f)

  override def product[B, C](fb: Kleisli[F, A, B], fc: Kleisli[F, A, C]): Kleisli[F, A, (B, C)] =
    Kleisli(a => F.product(fb.run(a), fc.run(a)))

  override def map[B, C](fa: Kleisli[F, A, B])(f: B => C): Kleisli[F, A, C] =
    fa.map(f)
}
```

**Closed as completed by peterneyens** 2017-04-21 07:34 UTC
Labels: release 0.1.0

**Comment by abdheshkumar** [comment] 2017-04-21 11:47
@peterneyens 
I tried to run your posted code but it is giving me a compile errors. The complete code is here
https://github.com/abdheshkumar/freestyle-example/blob/master/src/test/scala/FreeFutureTest.scala#L89

**Compilation Errors:**

`Error:(107, 7) no type parameters for method interpretAp: (implicit evidence$1: cats.Monad[M], implicit fInterpreter: cats.arrow.FunctionK[F,M])cats.arrow.FunctionK[[β$1$]cats.free.FreeApplicative[F,β$1$],M] exist so that it can be applied to arguments (cats.Monad[[γ$0$]cats.data.Kleisli[scala.concurrent.Future,String,γ$0$]], Algebra.Validation.Handler[Interpreters.ParValidator])
 --- because ---
argument expression's type is not compatible with formal parameter type;
 found   : cats.Monad[[γ$0$]cats.data.Kleisli[scala.concurrent.Future,String,γ$0$]]
 required: cats.Monad[?M]
      interpretAp(parValidatorMonad, implicitly[Algebra.Validation.Handler[ParValidator]])
Error:(107, 19) type mismatch;
 found   : cats.Monad[[γ$0$]cats.data.Kleisli[scala.concurrent.Future,String,γ$0$]]
 required: cats.Monad[M]
      interpretAp(parValidatorMonad, implicitly[Algebra.Validation.Handler[ParValidator]])
Error:(107, 48) type mismatch;
 found   : Algebra.Validation.Handler[Interpreters.ParValidator]
 required: cats.arrow.FunctionK[F,M]
      interpretAp(parValidatorMonad, implicitly[Algebra.Validation.Handler[ParValidator]])
Error:(107, 18) type mismatch;
 found   : cats.arrow.FunctionK[[β$1$]cats.free.FreeApplicative[F,β$1$],M]
 required: freestyle.ParInterpreter[Algebra.Validation.Op,Interpreters.ParValidator]
    (which expands to)  cats.arrow.FunctionK[[β$1$]cats.free.FreeApplicative[Algebra.Validation.Op,β$1$],Interpreters.ParValidator]
      interpretAp(parValidatorMonad, implicitly[Algebra.Validation.Handler[ParValidator]])`

**Comment by peterneyens** [comment] 2017-04-21 12:01
@abdheshkumar Specifying the type of the `Monad` instance seems to work:

```scala
val parValidatorMonad: Monad[ParValidator] = KleisliMonad.kleisliMonad[Future, String]
```

**Comment by abdheshkumar** [comment] 2017-04-21 12:09
@peterneyens 
Awesome! It works. 
Thank you so much for help and support!
